# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningServiceStub:
    """=========================================================
    SERVICE PRINCIPAL : ce que le serveur expose aux clients
    (RPC - Remote Procedure Call, chapitre 4)
    =========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/federated.FederatedLearningService/RegisterClient',
                request_serializer=federated__pb2.RegisterRequest.SerializeToString,
                response_deserializer=federated__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/federated.FederatedLearningService/GetGlobalModel',
                request_serializer=federated__pb2.ModelRequest.SerializeToString,
                response_deserializer=federated__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.SendLocalUpdate = channel.unary_unary(
                '/federated.FederatedLearningService/SendLocalUpdate',
                request_serializer=federated__pb2.LocalUpdate.SerializeToString,
                response_deserializer=federated__pb2.UpdateAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/federated.FederatedLearningService/Heartbeat',
                request_serializer=federated__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=federated__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ElectionMessage = channel.unary_unary(
                '/federated.FederatedLearningService/ElectionMessage',
                request_serializer=federated__pb2.ElectionRequest.SerializeToString,
                response_deserializer=federated__pb2.ElectionResponse.FromString,
                _registered_method=True)


class FederatedLearningServiceServicer:
    """=========================================================
    SERVICE PRINCIPAL : ce que le serveur expose aux clients
    (RPC - Remote Procedure Call, chapitre 4)
    =========================================================
    """

    def RegisterClient(self, request, context):
        """Un client s'enregistre auprès du serveur (lui obtient un nom plat + adresse)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Le serveur envoie le modèle global courant à un client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLocalUpdate(self, request, context):
        """Le client envoie ses poids locaux entraînés (mise à jour FedAvg)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat : pour la tolérance aux pannes (détection de panne via timeout)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectionMessage(self, request, context):
        """Élection de leader (Bully) : un client annonce sa candidature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=federated__pb2.RegisterRequest.FromString,
                    response_serializer=federated__pb2.RegisterResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=federated__pb2.ModelRequest.FromString,
                    response_serializer=federated__pb2.ModelResponse.SerializeToString,
            ),
            'SendLocalUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocalUpdate,
                    request_deserializer=federated__pb2.LocalUpdate.FromString,
                    response_serializer=federated__pb2.UpdateAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=federated__pb2.HeartbeatRequest.FromString,
                    response_serializer=federated__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ElectionMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectionMessage,
                    request_deserializer=federated__pb2.ElectionRequest.FromString,
                    response_serializer=federated__pb2.ElectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.FederatedLearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated.FederatedLearningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearningService:
    """=========================================================
    SERVICE PRINCIPAL : ce que le serveur expose aux clients
    (RPC - Remote Procedure Call, chapitre 4)
    =========================================================
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedLearningService/RegisterClient',
            federated__pb2.RegisterRequest.SerializeToString,
            federated__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedLearningService/GetGlobalModel',
            federated__pb2.ModelRequest.SerializeToString,
            federated__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLocalUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedLearningService/SendLocalUpdate',
            federated__pb2.LocalUpdate.SerializeToString,
            federated__pb2.UpdateAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedLearningService/Heartbeat',
            federated__pb2.HeartbeatRequest.SerializeToString,
            federated__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ElectionMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedLearningService/ElectionMessage',
            federated__pb2.ElectionRequest.SerializeToString,
            federated__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
